### ISSUE TITLE
build_runner ^1.5.2 is incompatible with less_dart

### ISSUE THREAD

**Issue by janvladimirmostert** [AdalbertoLacruz/less_dart#21]
I'm trying to get less_dart working with the latest angular package, 5.3.1 (migrating from Angular 2 to 4 and now to 5), but no matter how much i move versions around (it's like playing pot-a-mole), less_dart seems to be depending on an old version of build_runner which is not compatible with the latest Angular package.

```
name: _____
version: 1.0.0
description: _______

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.3.1
  angular_router: ^2.0.0-alpha+22
  angular_forms: ^2.1.2
  event_bus: any
  http: any
  js: ^0.6.0
  less_dart: any
  logging: "^0.11.3+1"
  html: any
  html_unescape: "^1.0.1+2"

dev_dependencies:
  angular_test: 2.3.0
  build_runner: ^1.5.2
  build_test: ^0.10.2
  build_web_compilers: ^1.2.0
  test: ^1.0.0

entry_points: ['*.less', '*.html']
```

```
The current Dart SDK version is 2.3.1.

Because no versions of build_runner match >1.5.2 <2.0.0 and build_runner 1.5.2 depends on build_config >=0.4.0 <0.4.1, build_runner ^1.5.2 requires build_config >=0.4.0 <0.4.1.
And because less_dart >=2.0.0 depends on build_config ^0.3.1 and less_dart <2.0.0 requires SDK version <2.0.0, build_runner ^1.5.2 is incompatible with less_dart.
So, because _________ depends on both less_dart any and build_runner ^1.5.2, version solving failed.
```
