### ISSUE TITLE
keyframe build

### ISSUE THREAD

**Issue by DmitriyLazarev** [AdalbertoLacruz/less_dart#28]
When I try to use something like that in LESS:

`
@keyframes abc {  

  0%, 10% {
    background-color: lightpink;
  }
}
`

it builds in CSS like:

`
@keyframes abc {

  0% 10% {
    background-color:lightpink
  }
}
`

The comma between 0 and 10 is lost and the styles for animation do not work.

**Comment by AdalbertoLacruz** [comment]
For me, it works nice.
I use @keyframes (lower letter).

**Comment by DmitriyLazarev** [comment]
Thank you for answer! But in @keyframes (lower letter) it also does not work.

**Comment by MrVladevoit** [comment]
@AdalbertoLacruz , i have bug too (( Can you help ?

**Comment by MrVladevoit** [comment]
@AdalbertoLacruz , this bug reproduced when you write short code for animation:

```less
@keyframes abc {

  0%,
  10% {
    background-color: #000000;
  }
}
```

We have: 
`@keyframes abc{0% 10%{background-color:black}}` - The comma between 0 and 10 is lost and the styles for animation do not work.


But i don't see bug, when i write: 
```less
@keyframes abc {

  0% {
   background-color: #000000;
  }

  10% {
    background-color: #000000;
  }

  100% {
    background-color: transparent;
  }
}
```

Can we fix shot @keyframes code ?
