### ISSUE TITLE
Problem with less variables imported from other packages

### ISSUE THREAD

**Issue by missvalentinep** [AdalbertoLacruz/less_dart#30]
### Problem
If you're importing less variables from other package, the changes to the variable are not seen by the builder, unless you remove .dart_tool & run rebuild.

### How to reproduce
Link to the repo to reproduce the issue - https://github.com/missvalentinep/less_variables_example 
1. Serve angular-app. Open the served app - the text is in green color
2. Change value of @chosen-color (in imported-styles/lib/src/basic_palette.less) to blue, for example. Save.
3. Rebuild finished with 1 outputs (2 actions)
4. Open the served app - the text is still in green color

5. Remove .dart_tool, serve the app once again
6. The text now has blue color.

### Additional
For some reason, when I tried to create a new project that had less variables and import it, the problem did not reproduce.
I'm not sure that the problem occurs precisely because of the variables file being in another package. I've encountered a similar issue, when the value of the less variable was changed inside the same project (perhaps, it has something to do with imports, since in that case they were used too, but from the same package) and no changes were visible. Unfortunately, I was unable to reproduce this issue on a small repo.

**Comment by AdalbertoLacruz** [comment]
Are you in the less_dart last version?

Your problem reminds me the issue with 2.3.5: [https://github.com/AdalbertoLacruz/less_dart/issues/26] yet resolved.
From your example the less_dart version is 2.3.5.

**Comment by missvalentinep** [comment]
I've checked - I'm using 2.3.8 because of the pub upgrade. But I've updated pubspecs in the example project to use ^2.3.8. Sorry for the confusion.

Were you able to reproduce the issue locally?

**Comment by AdalbertoLacruz** [comment]
OK. You must use package notation inside the package.

So, in the file: lib\palette.less in the  imported_styles package, replace:

@import (reference) "src/basic_palette.less";

to 

@import (reference) "packages/imported_styles/src/basic_palette.less";

The less builder needs to know what files are changed and the package notation helps.

**Comment by missvalentinep** [comment]
@AdalbertoLacruz that seems to solve the issue, thank you! Don't you think it's a bug that this works only with package notation?

**Comment by AdalbertoLacruz** [comment]
The package notation is a design requirement in the less builder and it's working!!
The builder see the files referenced to the main app.
If you don't want to use package notation must define an include:

In main app define a build.yaml file:

```
targets:
  $default:
    builders:
      less_dart:
        options:
          entry_points: ['*.less']
          include_path: 'packages/imported_styles/src'
```

in package define a build.yaml file:

```
targets:
  $default:
    builders:
      less_dart:
        options:
          entry_points: ['*.less', '!/src/*.less']
          include_path: 'packages/imported_styles/src'
```

and now inside the package change

`@import (reference) "src/basic_palette.less";`

to

`@import (reference) "basic_palette.less";`
