### ISSUE TITLE
Add capability to compile /deep/

### ISSUE THREAD

**Issue by luisvt** [AdalbertoLacruz/less_dart#4]
for example:

``` less
html /deep/ {
  input {
    color: blue;
  }

  button {
    color: red;
  }
}
```

should be compiled as:

``` css
html /deep/ input {
  color: blue;
}
html /deep/ button {
  color: red;
}
```
